# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('iscompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskPreviliges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('iscompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPreviliges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(default='sds', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskpreviliges',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
        migrations.AddField(
            model_name='taskpreviliges',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Group'),
        ),
        migrations.AddField(
            model_name='taskpreviliges',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Task'),
        ),
        migrations.AddField(
            model_name='subtaskpreviliges',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
        migrations.AddField(
            model_name='subtaskpreviliges',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Group'),
        ),
        migrations.AddField(
            model_name='subtaskpreviliges',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Task'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Task'),
        ),
        migrations.AddField(
            model_name='group',
            name='employee',
            field=models.ManyToManyField(to='TMS.Employee'),
        ),
    ]
