# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_auto_20170826_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
