# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_auto_20170826_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
