# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0004_auto_20170826_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskpreviliges',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
    ]
