# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0005_auto_20170826_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskpreviliges',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
        migrations.AlterField(
            model_name='taskpreviliges',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
        migrations.AlterField(
            model_name='taskpreviliges',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Group'),
        ),
    ]
