# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0008_auto_20170826_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='progress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
