# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0010_auto_20170826_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='subtask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee'),
        ),
    ]
