# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0011_auto_20170826_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Title',
        ),
    ]
