# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0013_auto_20170826_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='subtaskpreviliges',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='subtaskpreviliges',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subtaskpreviliges',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='taskpreviliges',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='taskpreviliges',
            name='group',
        ),
        migrations.RemoveField(
            model_name='taskpreviliges',
            name='task',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.DeleteModel(
            name='SubTaskPreviliges',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskPreviliges',
        ),
    ]
