# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0014_auto_20170826_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('iscompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskPreviliges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('iscompleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPreviliges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Employee')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TMS.Group')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Task')),
            ],
        ),
        migrations.AddField(
            model_name='subtaskpreviliges',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Task'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMS.Task'),
        ),
    ]
